# Generated by Django 4.0 on 2022-03-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0003_alter_answer_body'),
        ('question', '0005_alter_question_heading'),
        ('votes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answerdownvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='answer.answer'),
        ),
        migrations.AlterField(
            model_name='answerupvote',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='answer.answer'),
        ),
        migrations.AlterField(
            model_name='questiondownvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downvotes', to='question.question'),
        ),
        migrations.AlterField(
            model_name='questionupvote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upvotes', to='question.question'),
        ),
    ]
