# Generated by Django 4.0 on 2021-12-16 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AskerProfile',
        ),
    ]
