# Generated by Django 4.0 on 2022-01-27 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0003_alter_question_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='heading',
            field=models.CharField(blank=True, default='test heading', max_length=100, null=True),
        ),
    ]
