# Generated by Django 4.0 on 2022-01-27 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0004_question_heading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='heading',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
