# Generated by Django 4.0 on 2022-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('question', '0007_alter_question_user_alter_questioncomment_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='tag',
            field=models.CharField(choices=[('Buddhism', 'Buddhism'), ('English', 'English'), ('Mathematics', 'Mathematics'), ('Geography', 'Geography'), ('Science', 'Science'), ('Commerce', 'Commerce'), ('Agriculture', 'Agriculture'), ('ICT', 'ICT'), ('Drama', 'Drama'), ('Art', 'Art'), ('Dance', 'Dance'), ('History', 'History'), ('Music', 'Music'), ('Health', 'Health')], default='Buddhism', max_length=15),
        ),
    ]
