# Generated by Django 4.0 on 2022-01-20 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('answer', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='body',
            field=models.TextField(verbose_name='Answer'),
        ),
    ]
