# Generated by Django 4.0 on 2022-01-25 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='askerprofile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='askerprofile',
            name='age',
        ),
        migrations.RemoveField(
            model_name='askerprofile',
            name='website',
        ),
    ]
