# Generated by Django 4.0 on 2022-01-25 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_askerprofile_address_remove_askerprofile_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='askerprofile',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='askerprofile',
            name='grade',
            field=models.CharField(blank=True, choices=[('10', '10'), ('11', '11')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='askerprofile',
            name='school',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
