# Generated by Django 4.0 on 2022-03-05 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_friendship'),
    ]

    operations = [
        migrations.AddField(
            model_name='friendship',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
