# Generated by Django 4.0 on 2022-03-08 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('user', '0006_alter_friendship_from_user_alter_friendship_to_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='askerprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='asker', to='auth.user'),
        ),
    ]
